displayName: Metrics in routers
type: middleware
iconPath: .assets/icon.png

import: github.com/MrNinso/statusdonrouters

summary: 'give metrics per router'

testData:
  ip: 192.168.0.17
  port: 1234
  serverPrefix: 'traefik'